### ISSUE TITLE
Sidebar Active Route

### ISSUE THREAD

**Issue by Nicklas185105** [horizon-ui/horizon-ui-chakra-pro-nextjs#3]
I just bought the Pro version, after seeing the live preview.

I can see that the live preview does not have this problem, so I am a bit confused about why the bought version has it :D

![image](https://user-images.githubusercontent.com/43750236/229609163-434ccbfd-9660-4a32-900c-25e0f2d9ecfa.png)

As you can see the page "NFT Page" is bold because its path is "nfts" and the marketplace has that in its path as well.

**Comment by simmmpleweb** [comment]
Hello, @Nicklas185105 ! Thank you for supporting Horizon! We solved the issue and we will upload the changes in the following minutes!
Regards, Vlad.
