### ISSUE TITLE
A lot of errors & warnings on initial project startup

### ISSUE THREAD

**Issue by Nicklas185105** [horizon-ui/horizon-ui-chakra-pro-nextjs#4]
# Initial project errors & warnings

So I just downloaded version 2.1.1, and ran `yarn install` and then `yarn dev`.

| Node Version | Yarn Version | Horizon Version |
| ------------ | ------------ | --------------- |
| v18.15.0     | 1.22.19      | 2.1.1           |

## Yarn install warnings

On the `yarn install` command, there were a few warnings, I don't think these have any effect on the overall project, but they look like this:

<details>
<summary>Console warnings</summary>

![yarn install](https://user-images.githubusercontent.com/43750236/229877255-b055b9dd-0945-430e-ba18-438cab2bef26.png)

</details>

## Running errors

When running `yarn dev` and opening the localhost, there are both hydration errors and a lot of console errors.

> A lot of the errors and warnings are pretty much the same, I have just included everything to give an overview of every error & warning that was printed to the browser console.

### Hydration Errors

The project starts out with 5 hydration errors, they look like this:

<details>
<summary><b>Hydration Error 1</b></summary>

![hydration error 1](https://user-images.githubusercontent.com/43750236/229877723-dba257a4-3418-4d21-be3b-7a4a9da5cb04.png)

</details>

<details>
<summary><b>Hydration Error 2</b></summary>

![hydration error 2](https://user-images.githubusercontent.com/43750236/229877798-a7e44919-5bc0-49e4-b1fd-6dd5d4a1ac35.png)

</details>

<details>
<summary><b>Hydration Error 3</b></summary>

![image](https://user-images.githubusercontent.com/43750236/229880124-a7440a44-8b9f-4eb1-b249-ee3397e13425.png)

</details>

<details>
<summary><b>Hydration Error 4</b></summary>

![image](https://user-images.githubusercontent.com/43750236/229880205-96972619-62bd-458d-91bf-bfc61304febb.png)

</details>

<details>
<summary><b>Hydration Error 5</b></summary>

![image](https://user-images.githubusercontent.com/43750236/229880260-c1147f0f-15fe-45f3-823b-80e94f0ae7b7.png)

</details>

<br>

> I have attached the console errors & warnings as files, as they have a lot of characters and make the issue go over the maximum character limit

### Console errors

[consoleErrors.md](https://github.com/horizon-ui/horizon-ui-chakra-pro-nextjs/files/11152720/consoleErrors.md)

### Console warnings

[consoleWarnings.md](https://github.com/horizon-ui/horizon-ui-chakra-pro-nextjs/files/11152707/consoleWarnings.md)

**Comment by simmmpleweb** [comment]
Hello, @Nicklas185105! Sorry for the late reply! Everything should be fine now! Use the same link to download the new archive! 😁
