### ISSUE TITLE
The Configurator Drawer and Sidebar are not closing correctly.

### ISSUE THREAD

**Issue by Nagesh-Kulkarni** [horizon-ui/horizon-ui-chakra-pro-nextjs#6]
When we open sidebar and close it, the sidebar is still visible, making it impossible to do other tasks and we need to refersh the page to fix the issue.

![Configurator_Drawer](https://github.com/horizon-ui/horizon-ui-chakra-pro-nextjs/assets/149987984/ac20b30f-f8b4-4de5-88b3-57edf9bb92fe)
![SideBar_Drawer png](https://github.com/horizon-ui/horizon-ui-chakra-pro-nextjs/assets/149987984/b3c7a699-7223-4a92-9e95-02663627a583)

**Comment by simmmpleweb** [comment]
Hello, @Nagesh-Kulkarni ! Fixed in the new realease.
Regards, Vlad
